[features]
seeds = false
[programs.localnet]
solana_twitter = "7mMqfBqmcpuevpDJzWgYmo421ZCKaB1GhFqfpuRcbst1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/hakngrow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
